import Head from 'next/head'
import Image from 'next/image'
import { useTranslation } from 'next-i18next'

import styles from '@/styles/Home.module.css'

import Navbar from '../../components/Navbar'
import metaverse from '../../../public/metaverse.png'
import { getStaticPaths, makeStaticProps } from '../../lib/getStatic'


export default function About() {
  const { t, u18n, ready } = useTranslation(['common', 'navbar', 'footer']);

  return (
    <>
      <Head>
        <title>TTSec</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className=''>
          About us!
        </div>
      </main>
    </>
  )
}


const getStaticProps = makeStaticProps(['common', 'navbar', 'footer'])
export { getStaticPaths, getStaticProps }
