import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import metaverse from '../../public/metaverse.png';
import { useTranslation } from 'react-i18next'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { t } = useTranslation('common');

  return (
    <>
      <Head>
        <title>TTSec</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className=''>
          {/* For the image & title */}
          <div className="relative">
            <Image src={metaverse} alt="background" className="w-full" />
            <div className="absolute inset-0 bg-black opacity-20"></div>
            <div className="absolute top-0 left-0 w-full h-full flex flex-col justify-center items-center">
              <h1 className="text-4xl text-white font-bold">TTSecurity</h1>
              <p className="text-lg text-white">Security should not be an afterthought</p>
            </div>
          </div>

          {/* For actual content */}
          <div className="container mx-auto px-4 py-6">
            <h1 className="pb-10 text-5xl font-extrabold dark:text-white">Services<small className="ml-2 font-semibold text-gray-500 dark:text-gray-400">by experts</small></h1>

            <h2 className="text-4xl font-bold dark:text-white pb-2">1-Consulting</h2>
            <p className='pb-5'>We offer to consult on cybersecurity matters ranging from zero-day low-level knowledge to business decisions requiring insight into cybersecurity.</p>

            <h2 className="text-4xl font-bold dark:text-white py-2">2-Penetration Testing</h2>
            <p className='pb-5'>Our team of certified red-team professionals can give you a penetration test to ensure that you are hardened for this ever-increasing world of cyber threats. Our penetration test includes a report outlining any findings and any suggestions.</p>

            <h2 className="text-4xl font-bold dark:text-white py-2">3-Endpoint Detection</h2>
            <p className='pb-5'>We help secure your endpoints by constantly monitoring any domains you possess for any weaknesses.</p>

            <h2 className="text-4xl font-bold dark:text-white py-2">4-Incident Response</h2>
            <p className='pb-5'>Was there just an incident? Do you need professionals to assess how much damage was done and how to mitigate the next one? Our team can do all these for you and give you recommendations to avoid the next one.</p>

          </div>
        </div>
      </main>
    </>
  )
}
